[program:coagri]
command=/var/www/coagri/venv/bin/gunicorn --config /var/www/coagri/CoAgri/CoAgri/gunicorn.conf.py CoAgri.wsgi:application
directory=/var/www/coagri/CoAgri/CoAgri
user=www-data
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/coagri.log
stderr_logfile=/var/log/supervisor/coagri_error.log
environment=PATH="/var/www/coagri/venv/bin"