# Generated by Django 5.2.5 on 2025-08-15 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashAccountHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('ACTIVITY', 'Activity'), ('ITEM', 'Item'), ('EXPENSE', 'Expense')], max_length=50)),
                ('expected_efficiency', models.CharField(blank=True, help_text="e.g., '1 acre/hour'", max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('seed_variety', models.CharField(max_length=100)),
                ('harvesting_days', models.PositiveIntegerField(help_text='Average days from sowing to harvest')),
                ('expected_yield', models.DecimalField(decimal_places=2, help_text='in tons per acre', max_digits=10)),
                ('features', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farmland',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('size', models.DecimalField(decimal_places=2, help_text='in acres', max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('infrastructure', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ADMIN', 'Admin'), ('OPERATION_DIRECTOR', 'Operation Director'), ('ZONE_MANAGER', 'Zone Manager'), ('FARM_MANAGER', 'Farm Manager'), ('SUPERVISOR', 'Supervisor'), ('AUDITOR', 'Auditor')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('district', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(limit_choices_to={'type': 'ACTIVITY'}, on_delete=django.db.models.deletion.CASCADE, to='farm.category')),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.ForeignKey(limit_choices_to={'type': 'EXPENSE'}, on_delete=django.db.models.deletion.PROTECT, to='farm.category')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='farm.farmland')),
            ],
        ),
        migrations.CreateModel(
            name='CashIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_by', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('head', models.ForeignKey(limit_choices_to={'type': 'INCOME'}, on_delete=django.db.models.deletion.PROTECT, to='farm.cashaccounthead')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_inflows', to='farm.farmland')),
            ],
        ),
        migrations.CreateModel(
            name='FarmPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_start', models.DateField()),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('actual_harvest_date', models.DateField(blank=True, null=True)),
                ('actual_yield', models.DecimalField(blank=True, decimal_places=2, help_text='in tons', max_digits=10, null=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.crop')),
            ],
        ),
        migrations.CreateModel(
            name='FarmPlanStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day_offset', models.PositiveIntegerField(help_text='Days from plan start date')),
                ('duration_days', models.PositiveIntegerField(default=1)),
                ('budgeted_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.activity')),
                ('parent_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='farm.farmplan')),
            ],
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_done', models.CharField(help_text="e.g., '2 acres', '500 liters'", max_length=100)),
                ('time_taken', models.DurationField(help_text="e.g., '4 hours 30 minutes'")),
                ('notes', models.TextField(blank=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.activity')),
                ('parent_plan_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_entries', to='farm.farmplanstep')),
            ],
            options={
                'verbose_name_plural': 'Daily Activities',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(help_text="e.g., 'kg', 'liter', 'unit'", max_length=50)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(limit_choices_to={'type': 'ITEM'}, on_delete=django.db.models.deletion.CASCADE, to='farm.category')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJUST', 'Adjustment')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.farmland')),
                ('related_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farm.dailyactivity')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.item')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='farm.farmland')),
                ('item', models.ForeignKey(help_text='e.g., Tractor, Sprayer', on_delete=django.db.models.deletion.CASCADE, to='farm.item')),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_id', models.CharField(max_length=50)),
                ('size', models.DecimalField(decimal_places=2, help_text='in acres', max_digits=10)),
                ('infrastructure', models.TextField(blank=True, null=True)),
                ('parent_farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='farm.farmland')),
            ],
        ),
        migrations.AddField(
            model_name='farmplan',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_plans', to='farm.plot'),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to='farm.plot'),
        ),
        migrations.CreateModel(
            name='CropProduce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, help_text='in tons', max_digits=10)),
                ('storage_location', models.CharField(max_length=255)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.crop')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.farmland')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.plot')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, help_text='in tons', max_digits=10)),
                ('price_per_ton', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyer', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('crop_produce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='farm.cropproduce')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('education', models.CharField(blank=True, max_length=100)),
                ('assigned_farm', models.ForeignKey(blank=True, help_text='For Farm Managers', null=True, on_delete=django.db.models.deletion.SET_NULL, to='farm.farmland')),
                ('assigned_plot', models.ForeignKey(blank=True, help_text='For Supervisors', null=True, on_delete=django.db.models.deletion.SET_NULL, to='farm.plot')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farm.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('assigned_zone', models.ForeignKey(blank=True, help_text='For Zone Managers', null=True, on_delete=django.db.models.deletion.SET_NULL, to='farm.zone')),
            ],
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='labor_used',
            field=models.ManyToManyField(to='farm.staff'),
        ),
        migrations.AddField(
            model_name='farmland',
            name='parent_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmlands', to='farm.zone'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_present', models.BooleanField(default=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.farmland')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.staff')),
            ],
            options={
                'unique_together': {('staff', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='farm.farmland')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.item')),
            ],
            options={
                'unique_together': {('farm', 'item')},
            },
        ),
    ]
