# Generated by Django 5.2.5 on 2025-08-15 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plot',
            unique_together={('parent_farm', 'plot_id')},
        ),
    ]
