# Generated by Django 5.2.5 on 2025-08-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_rename_budgeted_cost_to_per_acre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyactivity',
            name='total_done',
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost per single unit of measure (e.g., cost per acre).', max_digits=10),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='quantity_done',
            field=models.DecimalField(decimal_places=2, default=1, help_text='The numerical amount of work done.', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='unit_of_measure',
            field=models.CharField(default=1, help_text="e.g., 'acres', 'liters', 'hours', 'units'", max_length=50),
            preserve_default=False,
        ),
    ]
