# Generated by Django 5.2.5 on 2025-08-16 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_change_labor_used_to_textfield'),
        ('farm', '0004_remove_dailyactivity_total_done_and_more'),
    ]

    operations = [
    ]
