# Generated by Django 5.2.5 on 2025-08-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_merge_20250816_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivity',
            name='vendor_name',
            field=models.CharField(blank=True, help_text='Name of vendor/contractor to whom payment will be made', max_length=255),
        ),
    ]
