# Generated by Django 5.2.5 on 2025-08-16 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_dailyactivity_vendor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyactivity',
            old_name='labor_used',
            new_name='labor_names',
        ),
        migrations.RemoveField(
            model_name='dailyactivity',
            name='cost_per_unit',
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='labor_cost_per_person',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='labor_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of laborers'),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='machine_cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='machine_used',
            field=models.BooleanField(default=False, help_text='Is machine used?'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price per unit for stock in', max_digits=10),
        ),
        migrations.CreateModel(
            name='ActivityItemUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('daily_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_usages', to='farm.dailyactivity')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.item')),
            ],
        ),
    ]
